insert into product (id, name, subtitle, description, brand, category, price, stock) values (1, 'Sony WH-1000XM5', 'Bezprzewodowe słuchawki z redukcją hałasu', 'Sony WH-1000XM5 to bezprzewodowe słuchawki z redukcją hałasu od Sony. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Sony', 'Audio', 1299.00, 15);
insert into product_connectivity (product_id, position, connectivity) values (1, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (1, 1, 'USB-C');
insert into product_image (product_id, position, url) values (1, 0, 'https://picsum.photos/seed/product-1-0/1200/800');
insert into product_image (product_id, position, url) values (1, 1, 'https://picsum.photos/seed/product-1-1/1200/800');
insert into product_image (product_id, position, url) values (1, 2, 'https://picsum.photos/seed/product-1-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (1, 0, 'Łączność', 'Bluetooth 5.2 · multipoint');
insert into product_specification (product_id, position, name, spec_value) values (1, 1, 'Czas pracy', 'Do 30 h z ANC');
insert into product_specification (product_id, position, name, spec_value) values (1, 2, 'Waga', '250 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (2, 'Bose QuietComfort Ultra', 'Flagowe słuchawki z dźwiękiem przestrzennym', 'Bose QuietComfort Ultra to flagowe słuchawki z dźwiękiem przestrzennym od Bose. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Bose', 'Audio', 1899.00, 8);
insert into product_connectivity (product_id, position, connectivity) values (2, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (2, 1, 'USB-C');
insert into product_image (product_id, position, url) values (2, 0, 'https://picsum.photos/seed/product-2-0/1200/800');
insert into product_image (product_id, position, url) values (2, 1, 'https://picsum.photos/seed/product-2-1/1200/800');
insert into product_image (product_id, position, url) values (2, 2, 'https://picsum.photos/seed/product-2-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (2, 0, 'Łączność', 'Bluetooth 5.3');
insert into product_specification (product_id, position, name, spec_value) values (2, 1, 'Czas pracy', 'Do 24 h');
insert into product_specification (product_id, position, name, spec_value) values (2, 2, 'Waga', '254 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (3, 'JBL Live 770NC', 'Słuchawki nauszne z adaptacyjnym ANC', 'JBL Live 770NC to słuchawki nauszne z adaptacyjnym ANC od JBL. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'JBL', 'Audio', 599.00, 20);
insert into product_connectivity (product_id, position, connectivity) values (3, 0, 'Bluetooth');
insert into product_image (product_id, position, url) values (3, 0, 'https://picsum.photos/seed/product-3-0/1200/800');
insert into product_image (product_id, position, url) values (3, 1, 'https://picsum.photos/seed/product-3-1/1200/800');
insert into product_image (product_id, position, url) values (3, 2, 'https://picsum.photos/seed/product-3-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (3, 0, 'Łączność', 'Bluetooth 5.3');
insert into product_specification (product_id, position, name, spec_value) values (3, 1, 'Czas pracy', 'Do 65 h');
insert into product_specification (product_id, position, name, spec_value) values (3, 2, 'Waga', '261 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (4, 'Samsung Galaxy Buds3', 'Douszne słuchawki z ANC', 'Samsung Galaxy Buds3 to douszne słuchawki z ANC od Samsung. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Samsung', 'Audio', 699.00, 0);
insert into product_connectivity (product_id, position, connectivity) values (4, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (4, 1, 'USB-C');
insert into product_image (product_id, position, url) values (4, 0, 'https://picsum.photos/seed/product-4-0/1200/800');
insert into product_image (product_id, position, url) values (4, 1, 'https://picsum.photos/seed/product-4-1/1200/800');
insert into product_image (product_id, position, url) values (4, 2, 'https://picsum.photos/seed/product-4-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (4, 0, 'Łączność', 'Bluetooth 5.4');
insert into product_specification (product_id, position, name, spec_value) values (4, 1, 'Czas pracy', 'Do 24 h z etui');
insert into product_specification (product_id, position, name, spec_value) values (4, 2, 'Wodoodporność', 'IP57');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (5, 'JBL Flip 6', 'Przenośny głośnik wodoodporny', 'JBL Flip 6 to przenośny głośnik wodoodporny od JBL. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'JBL', 'Audio', 549.00, 25);
insert into product_connectivity (product_id, position, connectivity) values (5, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (5, 1, 'USB-C');
insert into product_image (product_id, position, url) values (5, 0, 'https://picsum.photos/seed/product-5-0/1200/800');
insert into product_image (product_id, position, url) values (5, 1, 'https://picsum.photos/seed/product-5-1/1200/800');
insert into product_image (product_id, position, url) values (5, 2, 'https://picsum.photos/seed/product-5-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (5, 0, 'Moc', '30 W');
insert into product_specification (product_id, position, name, spec_value) values (5, 1, 'Czas pracy', 'Do 12 h');
insert into product_specification (product_id, position, name, spec_value) values (5, 2, 'Wodoodporność', 'IP67');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (6, 'Logitech MX Master 3S', 'Precyzyjna mysz do pracy', 'Logitech MX Master 3S to precyzyjna mysz do pracy od Logitech. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Logitech', 'Akcesoria', 449.00, 30);
insert into product_connectivity (product_id, position, connectivity) values (6, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (6, 1, 'USB-C');
insert into product_image (product_id, position, url) values (6, 0, 'https://picsum.photos/seed/product-6-0/1200/800');
insert into product_image (product_id, position, url) values (6, 1, 'https://picsum.photos/seed/product-6-1/1200/800');
insert into product_image (product_id, position, url) values (6, 2, 'https://picsum.photos/seed/product-6-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (6, 0, 'Rozdzielczość', '8000 DPI');
insert into product_specification (product_id, position, name, spec_value) values (6, 1, 'Czas pracy', 'Do 70 dni');
insert into product_specification (product_id, position, name, spec_value) values (6, 2, 'Waga', '141 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (7, 'Logitech MX Keys S', 'Bezprzewodowa klawiatura z podświetleniem', 'Logitech MX Keys S to bezprzewodowa klawiatura z podświetleniem od Logitech. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Logitech', 'Akcesoria', 499.00, 12);
insert into product_connectivity (product_id, position, connectivity) values (7, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (7, 1, 'USB-C');
insert into product_image (product_id, position, url) values (7, 0, 'https://picsum.photos/seed/product-7-0/1200/800');
insert into product_image (product_id, position, url) values (7, 1, 'https://picsum.photos/seed/product-7-1/1200/800');
insert into product_image (product_id, position, url) values (7, 2, 'https://picsum.photos/seed/product-7-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (7, 0, 'Układ', 'US');
insert into product_specification (product_id, position, name, spec_value) values (7, 1, 'Czas pracy', 'Do 10 dni z podświetleniem');
insert into product_specification (product_id, position, name, spec_value) values (7, 2, 'Waga', '810 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (8, 'Anker Nano 65W', 'Kompaktowa ładowarka GaN', 'Anker Nano 65W to kompaktowa ładowarka GaN od Anker. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Anker', 'Akcesoria', 149.00, 40);
insert into product_connectivity (product_id, position, connectivity) values (8, 0, 'USB-C');
insert into product_image (product_id, position, url) values (8, 0, 'https://picsum.photos/seed/product-8-0/1200/800');
insert into product_image (product_id, position, url) values (8, 1, 'https://picsum.photos/seed/product-8-1/1200/800');
insert into product_image (product_id, position, url) values (8, 2, 'https://picsum.photos/seed/product-8-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (8, 0, 'Moc', '65 W');
insert into product_specification (product_id, position, name, spec_value) values (8, 1, 'Porty', '1× USB-C');
insert into product_specification (product_id, position, name, spec_value) values (8, 2, 'Waga', '112 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (9, 'Anker PowerCore 20000', 'Powerbank o dużej pojemności', 'Anker PowerCore 20000 to powerbank o dużej pojemności od Anker. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Anker', 'Akcesoria', 199.00, 3);
insert into product_connectivity (product_id, position, connectivity) values (9, 0, 'USB-C');
insert into product_image (product_id, position, url) values (9, 0, 'https://picsum.photos/seed/product-9-0/1200/800');
insert into product_image (product_id, position, url) values (9, 1, 'https://picsum.photos/seed/product-9-1/1200/800');
insert into product_image (product_id, position, url) values (9, 2, 'https://picsum.photos/seed/product-9-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (9, 0, 'Pojemność', '20 000 mAh');
insert into product_specification (product_id, position, name, spec_value) values (9, 1, 'Moc', '22,5 W');
insert into product_specification (product_id, position, name, spec_value) values (9, 2, 'Waga', '356 g');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (10, 'Samsung Galaxy S25', 'Smartfon z ekranem 6,2"', 'Samsung Galaxy S25 to smartfon z ekranem 6,2" od Samsung. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Samsung', 'Smartfony', 3999.00, 10);
insert into product_connectivity (product_id, position, connectivity) values (10, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (10, 1, 'USB-C');
insert into product_connectivity (product_id, position, connectivity) values (10, 2, 'Wi-Fi');
insert into product_image (product_id, position, url) values (10, 0, 'https://picsum.photos/seed/product-10-0/1200/800');
insert into product_image (product_id, position, url) values (10, 1, 'https://picsum.photos/seed/product-10-1/1200/800');
insert into product_image (product_id, position, url) values (10, 2, 'https://picsum.photos/seed/product-10-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (10, 0, 'Ekran', '6,2" AMOLED 120 Hz');
insert into product_specification (product_id, position, name, spec_value) values (10, 1, 'Pamięć', '256 GB');
insert into product_specification (product_id, position, name, spec_value) values (10, 2, 'Bateria', '4000 mAh');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (11, 'Sony Xperia 10 VI', 'Smartfon z baterią na dwa dni', 'Sony Xperia 10 VI to smartfon z baterią na dwa dni od Sony. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Sony', 'Smartfony', 1799.00, 0);
insert into product_connectivity (product_id, position, connectivity) values (11, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (11, 1, 'USB-C');
insert into product_connectivity (product_id, position, connectivity) values (11, 2, 'Wi-Fi');
insert into product_image (product_id, position, url) values (11, 0, 'https://picsum.photos/seed/product-11-0/1200/800');
insert into product_image (product_id, position, url) values (11, 1, 'https://picsum.photos/seed/product-11-1/1200/800');
insert into product_image (product_id, position, url) values (11, 2, 'https://picsum.photos/seed/product-11-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (11, 0, 'Ekran', '6,1" OLED');
insert into product_specification (product_id, position, name, spec_value) values (11, 1, 'Pamięć', '128 GB');
insert into product_specification (product_id, position, name, spec_value) values (11, 2, 'Bateria', '5000 mAh');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (12, 'Samsung Galaxy Book4', 'Lekki laptop do pracy i nauki', 'Samsung Galaxy Book4 to lekki laptop do pracy i nauki od Samsung. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Samsung', 'Komputery', 3499.00, 6);
insert into product_connectivity (product_id, position, connectivity) values (12, 0, 'Bluetooth');
insert into product_connectivity (product_id, position, connectivity) values (12, 1, 'USB-C');
insert into product_connectivity (product_id, position, connectivity) values (12, 2, 'Wi-Fi');
insert into product_image (product_id, position, url) values (12, 0, 'https://picsum.photos/seed/product-12-0/1200/800');
insert into product_image (product_id, position, url) values (12, 1, 'https://picsum.photos/seed/product-12-1/1200/800');
insert into product_image (product_id, position, url) values (12, 2, 'https://picsum.photos/seed/product-12-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (12, 0, 'Procesor', 'Intel Core 5');
insert into product_specification (product_id, position, name, spec_value) values (12, 1, 'Pamięć RAM', '16 GB');
insert into product_specification (product_id, position, name, spec_value) values (12, 2, 'Dysk', '512 GB SSD');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (13, 'Logitech MX Brio', 'Kamera internetowa 4K', 'Logitech MX Brio to kamera internetowa 4K od Logitech. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Logitech', 'Komputery', 999.00, 9);
insert into product_connectivity (product_id, position, connectivity) values (13, 0, 'USB-C');
insert into product_image (product_id, position, url) values (13, 0, 'https://picsum.photos/seed/product-13-0/1200/800');
insert into product_image (product_id, position, url) values (13, 1, 'https://picsum.photos/seed/product-13-1/1200/800');
insert into product_image (product_id, position, url) values (13, 2, 'https://picsum.photos/seed/product-13-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (13, 0, 'Rozdzielczość', '4K 30 fps');
insert into product_specification (product_id, position, name, spec_value) values (13, 1, 'Pole widzenia', '90°');
insert into product_specification (product_id, position, name, spec_value) values (13, 2, 'Mikrofony', '2');
insert into product (id, name, subtitle, description, brand, category, price, stock) values (14, 'Samsung T7 1TB', 'Przenośny dysk SSD', 'Samsung T7 1TB to przenośny dysk SSD od Samsung. Sprawdzi się na co dzień w domu, w pracy i w podróży.', 'Samsung', 'Komputery', 459.00, 18);
insert into product_connectivity (product_id, position, connectivity) values (14, 0, 'USB-C');
insert into product_image (product_id, position, url) values (14, 0, 'https://picsum.photos/seed/product-14-0/1200/800');
insert into product_image (product_id, position, url) values (14, 1, 'https://picsum.photos/seed/product-14-1/1200/800');
insert into product_image (product_id, position, url) values (14, 2, 'https://picsum.photos/seed/product-14-2/1200/800');
insert into product_specification (product_id, position, name, spec_value) values (14, 0, 'Pojemność', '1 TB');
insert into product_specification (product_id, position, name, spec_value) values (14, 1, 'Prędkość', 'Do 1050 MB/s');
insert into product_specification (product_id, position, name, spec_value) values (14, 2, 'Waga', '58 g');
select setval(pg_get_serial_sequence('product', 'id'), (select max(id) from product));
